Implement due date column in experiment table view [SCI-7406]
scinote-eln/scinote-web pull request #4646
Opened 2022-11-23 18:56 UTC by rekonder

Jira ticket: [SCI-7406](https://scinote.atlassian.net/browse/SCI-7406)

### What was done
Implement the due date column in the experiment table view

2022-11-24 11:55 UTC, aignatov-bio requested changes

2022-11-24 11:55 UTC, aignatov-bio commented on app/assets/javascripts/experiments/table.js
> +      this.initDueDatePicker(`#calendarDueDate${data.columns.filter(k => k.column_type === 'id')[0].data.id}`);
Can you move it to separate action and just call this action here.
And you have ID available here with just `id`, check line 56

2022-11-24 11:55 UTC, aignatov-bio commented on app/services/experiments/table_view_service.rb
> +          locals: { my_module: my_module,
pass to partial only `my_module` and `user`. And call all other helpers inside partial. This will be much more cleaner.

2022-11-30 14:29 UTC, artoscinote commented on app/controllers/my_modules_controller.rb
> +            tabel_due_date_label: {
Probably 'table', not 'tabel'?

2022-12-01 14:00 UTC, aignatov-bio approved these changes

2022-12-02 10:01 UTC, merged