Upgrade TinyMCE to 6.3, fix issues [SCI-7574]
scinote-eln/scinote-web pull request #4704
Opened 2022-12-09 11:54 UTC by artoscinote

Jira ticket: [SCI-7475](https://scinote.atlassian.net/browse/SCI-7475)

### What was done
Upgraded to TinyMCE 6.3

2022-12-09 12:03 UTC, aignatov-bio requested changes
Fix hound issues

2022-12-09 12:03 UTC, aignatov-bio commented on app/javascript/vue/shared/tinymce.vue
> +          <input type="hidden" id="tiny-mce-images" name="tiny_mce_images" value="[]">
I think better fix JS, which can be multiple inputs on the task. If you load few editors

2022-12-09 12:08 UTC, artoscinote commented on app/javascript/vue/protocol/container.vue
> -        this.protocol.attributes = protocol.data.attributes
I changed the way data is sent with the update event, so we don't have to call data.data all the time. I tested on all types (notes, protocol description, step texts).

2022-12-23 13:14 UTC, aignatov-bio approved these changes

2022-12-23 13:15 UTC, merged