Hover for sorting function in other SN tables (with sorting function) [SCI-7562]
scinote-eln/scinote-web pull request #4888
Opened 2023-01-25 15:52 UTC by sboursen-scinote

Jira ticket: [SCI-7562](https://scinote.atlassian.net/browse/SCI-7562)

### What was done
- [x] Changed the cursor pointer design when hovering over a datatable header.
- [x] Changed the default sorting for the tables according to the following data: 

Table | Predefined sorting 
-- | -- |
Label templates | Name |
Reports | Last update date (the latest date is the first listed) |
Teams | Team (name of the team) |
(One) Team | Name |
Members | Name | 
Organization - System log | Timestamp (the latest date is the first listed) |
Inventories | Name |
Archived inventories | Name |
Items (one inventory) | Name |
Archived Items (of one inventory) | Name |

#### ToDo:
There is a bug preventing the display of the default sorting of inventory items for archived inventories.
Need to learn more about the desired behavior.

2023-02-06 10:16 UTC, artoscinote approved these changes

2023-02-27 10:57 UTC, aignatov-bio requested changes
Ticket is not done, read the ticket again.

2023-02-28 11:46 UTC, sboursen-scinote commented
> Ticket is not done, read the ticket again.

I don't see what's missing.
Please provide more information.

2023-02-28 11:49 UTC, sboursen-scinote commented on app/assets/stylesheets/extend/datatable.scss
> +        &:not(#select-all) {
The new pointer icon was added following the request of the product team.

2023-03-07 09:56 UTC, aignatov-bio approved these changes

2023-03-07 13:10 UTC, merged