FE manage devices (table view) + revoking the device [SCI-7633]
scinote-eln/scinote-web pull request #4920
Opened 2023-02-01 17:38 UTC by G-Chubinidze

Jira ticket: [SCI-7633](https://scinote.atlassian.net/browse/SCI-7633)

### What was done
_frontend for logged devices and their revokation modal, note: we dont save the logged devices data yet so i created a dummy variable, also, the revokation functionality isn't implemented yet. just FE_

2023-02-07 12:42 UTC, artoscinote requested changes

2023-02-07 12:42 UTC, artoscinote commented on app/assets/javascripts/sitewide/device_revocation.js
> +});
Do we need this? I think for just opening the modal, we can use:
`data-toggle="modal" data-target="#revokeDeviceBtn"`
on the button.

2023-02-07 12:42 UTC, artoscinote commented on app/views/users/registrations/edit.html.erb
> +<%= render partial: 'device_revocation_modal' %>
I would move this partial inside the manage_devices partial, because it's required for it to work.

2023-03-14 11:22 UTC, rekonder requested changes

2023-03-14 11:22 UTC, rekonder commented on app/views/users/registrations/_manage_devices.html.erb
> +<% mobile_app_devices = [] %>
Fetch real data

2023-03-17 12:44 UTC, merged