Protocol templates - delete all steps (tasks screen) [SCI-7904]
scinote-eln/scinote-web pull request #4955
Opened 2023-02-09 15:12 UTC by sboursen-scinote

Jira ticket: [SCI-7904](https://scinote.atlassian.net/browse/SCI-7904)

### What was done
- Updated the modal text (locals).
- Updated the style to fit the new design.

2023-02-09 15:15 UTC, sboursen-scinote commented on app/assets/stylesheets/extend/bootstrap.scss
> +      position: absolute;
This is really weird!

2023-02-27 10:53 UTC, aignatov-bio requested changes
Do not invent new modal, you need just replace text

2023-02-28 11:33 UTC, sboursen-scinote commented
> Do not invent new modal, you need just replace text

No problem
I thought applying the new style is part of the ticket.

2023-02-28 14:26 UTC, aignatov-bio approved these changes

2023-02-28 14:33 UTC, merged