Protocol templates - unlink action and modal changes [SCI-7909]
scinote-eln/scinote-web pull request #4975
Opened 2023-02-14 15:28 UTC by sboursen-scinote

Jira ticket: [SCI-7909](https://scinote.atlassian.net/browse/SCI-7909)

### What was done
- Update the text and style of the unlink protocol modal

2023-02-14 15:36 UTC, sboursen-scinote commented on app/assets/javascripts/protocols/index.js
> +    $('.protocols-index').on('click', '#protocol-versions-modal .delete-draft', function(e) {
I didn't even touch this file!

2023-02-27 10:50 UTC, aignatov-bio requested changes
Same fixes as in revert modal PR

2023-02-28 11:14 UTC, aignatov-bio requested changes

2023-02-28 11:14 UTC, aignatov-bio commented on app/assets/javascripts/my_modules/protocols.js
> +      const {
revert it

2023-02-28 14:22 UTC, aignatov-bio approved these changes

2023-02-28 14:38 UTC, merged