Add version modal to protocol show page [SCI-7985]
scinote-eln/scinote-web pull request #5018
Opened 2023-02-23 12:12 UTC by aignatov-bio

Jira ticket: [SCI-7985](https://scinote.atlassian.net/browse/SCI-7985)

### What was done
Add version modal to protocol show page

2023-02-23 12:31 UTC, rekonder requested changes

2023-02-23 12:31 UTC, rekonder commented on app/javascript/vue/protocol/protocolMetadata.vue
> +        console.log(this.protocol.attributes.urls.versions_modal_url)
Remove this

2023-02-23 12:31 UTC, rekonder commented on app/javascript/packs/vue/protocol.js
> +    console.log(e)
Solve this

2023-02-23 13:15 UTC, rekonder approved these changes

2023-02-23 14:05 UTC, okriuchykhin commented on app/controllers/protocols_controller.rb
> +      Rails.logger.error e.message
you forgot to rollback transaction

2023-02-23 14:05 UTC, okriuchykhin requested changes
Check comments

2023-02-24 15:17 UTC, okriuchykhin approved these changes

2023-02-24 15:17 UTC, merged