Add disclaimer modal [SCI-7960]
scinote-eln/scinote-web pull request #5112
Opened 2023-03-09 10:59 UTC by aignatov-bio

Jira ticket: [SCI-7960](https://scinote.atlassian.net/browse/SCI-7960)

### What was done
Add disclaimer modal

2023-04-13 09:07 UTC, okriuchykhin commented on app/models/user.rb
> +  def self.login_disclaimer
move it to ApplicationHelper

2023-04-13 09:08 UTC, okriuchykhin commented on app/views/users/shared/_azure_sign_in_links.html.erb
> +    <%= form_tag user_customazureactivedirectory_omniauth_authorize_path(provider: config['provider_name']), method: :post, id: "azureAdForm" do %>
probably it is better to use class, as we can have many such elements?

2023-04-13 09:09 UTC, okriuchykhin requested changes
See the comments

2023-04-17 09:24 UTC, artoscinote approved these changes

2023-04-17 09:25 UTC, merged