Fix revert protocol action for linked task changes [SCI-8110]
scinote-eln/scinote-web pull request #5125
Opened 2023-03-13 08:33 UTC by rekonder

Jira ticket: [SCI-8110](https://scinote.atlassian.net/browse/SCI-8110)

### What was done
Fix revert protocol action for linked task changes

2023-03-13 10:44 UTC, aignatov-bio requested changes

2023-03-13 10:44 UTC, aignatov-bio commented on app/javascript/vue/protocol/mixins/attachments.js
> +                setTimeout(() => {
Did you try 'nextTick` helper?

2023-03-13 12:03 UTC, rekonder commented on app/javascript/vue/protocol/mixins/attachments.js
> +                setTimeout(() => {
Try it. Did not work.

2023-03-14 11:59 UTC, aignatov-bio approved these changes

2023-03-14 12:03 UTC, merged