Refactor left/top navigation [SCI-8055]
scinote-eln/scinote-web pull request #5175
Opened 2023-03-22 08:45 UTC by aignatov-bio

Jira ticket: [SCI-8055](https://scinote.atlassian.net/browse/SCI-8055)

### What was done
Refactor left/top navigation

2023-03-22 11:00 UTC, artoscinote requested changes

2023-03-22 11:23 UTC, aignatov-bio commented on config/locales/en.yml
> +      core_version: "SciNote version"
No, it is changed, now it is just a button that opens the modal with the versions.

<img width="320" alt="Screenshot 2023-03-22 at 12 23 14" src="https://user-images.githubusercontent.com/47317017/226889893-2fae3d43-425e-4e40-922e-bd9206df0f7a.png">

2023-03-22 11:24 UTC, aignatov-bio commented on app/controllers/navigations_controller.rb
> +      url: Rails.application.routes.url_helpers.teams_path
They include an instance of the controller, not to class.

2023-03-22 11:36 UTC, aignatov-bio commented on app/controllers/navigations_controller.rb
> +  skip_before_action :authenticate_user!
It is also for the sign-in page. We just show the logo.

2023-03-22 12:43 UTC, artoscinote requested changes

2023-03-23 08:59 UTC, artoscinote approved these changes

2023-03-23 10:46 UTC, merged