Implement basic select/search-select components in vue [SCI-8249]
scinote-eln/scinote-web pull request #5341
Opened 2023-04-24 10:52 UTC by artoscinote

Jira ticket: [SCI-8249](https://scinote.atlassian.net/browse/SCI-8249)

### What was done
Implement basic select/search-select components in vue

2023-04-25 08:28 UTC, aignatov-bio requested changes
Will be nice to have feature to open up if not space at bottom

2023-04-25 08:28 UTC, aignatov-bio commented on app/javascript/vue/shared/select_search.vue
> +      placeholder: { type: String, default: 'Select' }
i18n

2023-04-25 08:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/select.scss
> +  border: 1px solid;
i think we must have borders as variables

2023-04-25 08:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/select.scss
> +  border-radius: 4px;
This also

2023-04-25 08:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/select.scss
> +      border-bottom-left-radius: 4px;
also variable

2023-04-25 08:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/select.scss
> +.sn-select {
It will be fixed height so better define the height

2023-04-25 08:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/select.scss
> +    top: 1.1em;
you can just define the parent container with the same height as select and center caret inside. Then you don't need this calculation.

2023-04-25 08:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/select.scss
> +    all: unset;
You need to cover long values, so it must be `...` 
And do we need different color for placeholder?

2023-04-25 08:28 UTC, aignatov-bio commented on app/javascript/vue/shared/select_search.vue
> +      options: { type: Array, default: [] },
Also, we need the ability so set value and define initial value

2023-04-25 08:32 UTC, aignatov-bio requested changes
Oh and one important thing - this dropdown must ignore overflow

2023-05-03 10:34 UTC, sboursen-scinote commented on app/javascript/vue/shared/select_search.vue
> +            console.log(data)
Please remove the `console.log`

2023-05-03 10:37 UTC, merged