Implement the bottom action toolbar - inventories [SCI-8299]
scinote-eln/scinote-web pull request #5416
Opened 2023-05-16 21:23 UTC by G-Chubinidze

Jira ticket: [SCI-8299](https://scinote.atlassian.net/browse/SCI-8299)

### What was done
_bottom action toolbar for inventories_

[SCI-8299]: https://scinote.atlassian.net/browse/SCI-8299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-05-18 07:47 UTC, artoscinote requested changes
Fix linter issues.

2023-05-23 12:28 UTC, aignatov-bio requested changes

2023-05-23 12:28 UTC, aignatov-bio commented on app/assets/stylesheets/shared/datatable.scss
> +    z-index: 90;
this not correct, rebase on develop must not be fixed.

2023-05-23 12:28 UTC, aignatov-bio commented on app/assets/javascripts/repositories/index.js
> +  $(document)
don't use document

2023-05-24 08:54 UTC, aignatov-bio requested changes
Fix hound

2023-05-24 10:06 UTC, aignatov-bio approved these changes

2023-05-24 10:06 UTC, merged