Position of opened drop down [SCI-8473]
scinote-eln/scinote-web pull request #5476
Opened 2023-05-25 06:53 UTC by G-Chubinidze

Jira ticket: [SCI-8473](https://scinote.atlassian.net/browse/SCI-8473)

### What was done
_added crisp edges & included user flyout_

2023-05-25 11:24 UTC, aignatov-bio requested changes

2023-05-25 11:24 UTC, aignatov-bio commented on app/assets/stylesheets/navigation/top_menu.scss
> +    top: calc(47px - 0.5em);
Make it nicer

2023-05-26 09:16 UTC, aignatov-bio requested changes

2023-05-26 09:16 UTC, aignatov-bio commented on app/assets/stylesheets/navigation/top_menu.scss
> +    top: 43px;
i mean just fix size of user button, so it will have same size as other buttons

2023-06-01 10:32 UTC, artoscinote approved these changes

2023-06-01 10:32 UTC, merged