Add move ability to attachments [SCI-9088]
scinote-eln/scinote-web pull request #6075
Opened 2023-08-24 13:57 UTC by aignatov-bio

Jira ticket: [SCI-9088](https://scinote.atlassian.net/browse/SCI-9088)

### What was done
Add move ability to attachments

2023-08-24 14:19 UTC, artoscinote requested changes
Fix linter issues.

2023-08-24 14:19 UTC, artoscinote commented on app/javascript/vue/shared/content/attachments.vue
> +        this.$emit('attachment:deleted', id, )
Remove this comma and space.

2023-08-28 09:06 UTC, artoscinote approved these changes

2023-08-28 09:22 UTC, okriuchykhin commented on app/controllers/assets_controller.rb
> +    rescue ActiveRecord::RecordInvalid
will the transaction be rolled backed?

2023-08-28 09:23 UTC, okriuchykhin commented on app/controllers/assets_controller.rb
> +        render json: { status: :ok }
why not simply use HTTP codes?

2023-08-28 09:26 UTC, okriuchykhin requested changes
check comments

2023-09-01 08:17 UTC, okriuchykhin approved these changes

2023-09-05 12:41 UTC, merged