Fix move_targets methods to only return active results; prevent moving elements to archived results [SCI-9403]
scinote-eln/scinote-web pull request #6321
Opened 2023-09-29 12:40 UTC by ivanscinote

Jira ticket: [SCI-9403](https://scinote.atlassian.net/browse/SCI-9403)

### What was done
- fix move_targets methods to only return active results
- prevent moving elements to archived results

2023-09-29 18:10 UTC, aignatov-bio requested changes

2023-09-29 18:10 UTC, aignatov-bio commented on app/controllers/assets_controller.rb
> +    case @assoc
This must be done by permission

2023-09-29 18:10 UTC, aignatov-bio commented on app/controllers/result_elements/tables_controller.rb
> +      target = @my_module.results.active.find_by(id: params[:target_id])
Also permission check

2023-09-29 18:10 UTC, aignatov-bio commented on app/controllers/result_elements/texts_controller.rb
> +      target = @my_module.results.active.find_by(id: params[:target_id])
Also permission check

2023-10-03 10:45 UTC, artoscinote approved these changes

2023-10-03 10:45 UTC, merged