CSS: Blank name error message on table [sci-9401]
scinote-eln/scinote-web pull request #6322
Opened 2023-10-02 03:42 UTC by G-Chubinidze

Jira ticket: [SCI-9401](https://scinote.atlassian.net/browse/SCI-9401)

### What was done
_css fixes for table and inline edit_

2023-10-02 10:39 UTC, aignatov-bio requested changes

2023-10-02 10:39 UTC, aignatov-bio commented on app/assets/stylesheets/shared/content/table.scss
> +    margin-bottom: 15px;
!?

2023-10-02 10:39 UTC, aignatov-bio commented on app/javascript/vue/shared/inline_edit.vue
> -            this.$refs.input.style.height = '0px';
It is required

2023-10-05 09:03 UTC, aignatov-bio approved these changes

2023-10-05 09:03 UTC, artoscinote approved these changes

2023-10-05 09:04 UTC, merged