Apply layout for Grover PDF library [SCI-9566]
scinote-eln/scinote-web pull request #6547
Opened 2023-10-27 12:45 UTC by ivanscinote

Jira ticket: [SCI-9566](https://scinote.atlassian.net/browse/SCI-9566)

### What was done
- apply styling that works with Grover library
- refactor perform method in pdf_job.rb

2023-10-30 09:47 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +      handle_error(e)
keep handling code here

2023-10-30 09:47 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +      cleanup
and same here

2023-10-30 09:52 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +      attach_pdf_to_report
it does much more than just attach

2023-10-30 09:57 UTC, artoscinote requested changes

2023-10-30 09:57 UTC, artoscinote commented on app/jobs/reports/pdf_job.rb
> +        @style_tag_options << { content: css_content }
can be written as

```
@style_tag_options = css_files.map do |file_name|
  { content: fetch_asset_content("#{file_name}.css") }
end
```

2023-10-30 09:57 UTC, artoscinote commented on app/jobs/reports/pdf_job.rb
> +      end
```
@script_tag_options = javascript_files.map do |file_name|
  { content: fetch_asset_content("#{file_name}.js") }
end
```

2023-10-30 12:06 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +      return file unless has_cover
move this condition out

2023-10-30 16:14 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +        @file = prepend_title_page(@file, @template, @report, @renderer, @style_tag_options, @script_tag_options)
these are all instance variables, no need to pass them as params

2023-10-30 16:19 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +        display_url: "#{Rails.application.config.force_ssl ? 'https' : 'http'}://" \
Rails.application.routes.default_url_options[:host]

2023-10-30 16:28 UTC, okriuchykhin requested changes
check how you use instance variables

2023-11-03 08:31 UTC, okriuchykhin commented on app/jobs/reports/pdf_job.rb
> +                     "#{Rails.application.secrets.mail_server_url}"
Rails.application.routes.default_url_options[:host]

2023-11-03 10:05 UTC, artoscinote approved these changes

2023-11-03 12:19 UTC, okriuchykhin approved these changes

2023-11-03 12:19 UTC, merged