Implement the 'Add relationship' modal, only front end [SCI-9671]
scinote-eln/scinote-web pull request #6637
Opened 2023-11-14 14:04 UTC by lasniscinote

Jira ticket: [SCI-9671](https://scinote.atlassian.net/browse/SCI-9671)

### What was done
Implemented front-end for the add relationship modal

2023-11-15 15:03 UTC, okriuchykhin commented on app/javascript/packs/vue/add_item_relationships.js
name it repository_item_relationships_modal.js

2023-11-15 15:04 UTC, okriuchykhin commented on app/javascript/vue/item_relationships/AddItemRelationshipsModal.vue
> +  name: 'AddItemRelationshipsModal',
call it RepositoryItemRelationshipsModal

2023-11-15 15:50 UTC, okriuchykhin commented on app/javascript/vue/repository_item_sidebar/RepositoryItemSidebar.vue
Remove autoformatting from here

2023-11-15 15:51 UTC, okriuchykhin commented on app/javascript/vue/shared/checklist_select.vue
> +            class="btn flex justify-between items-center w-full outline-none border-[1px] bg-white rounded p-2 pl-4
is it a global change? Won't it affect other parts?

2023-11-28 08:30 UTC, artoscinote requested changes

2023-11-28 08:30 UTC, artoscinote commented on app/javascript/vue/item_relationships/RepositoryItemRelationshipsModal.vue
> +      if ((this.selectedInventoryValue !== null) && (this.selectedRelationshipValue !== null) && (this.selectedItemValues.length > 0)) {
just return the expression

2023-11-28 08:30 UTC, artoscinote commented on app/javascript/vue/item_relationships/RepositoryItemRelationshipsModal.vue
> +      this.$delete(this.data, 'selectedRelationshipValue');
try and remove this delete part and test again

2023-11-28 08:30 UTC, artoscinote commented on app/javascript/vue/repository_row/manage_stock_value_modal.vue
> +                  :shouldRecalcPosition="true"
remove changes to this file from this PR

2023-11-28 11:46 UTC, artoscinote approved these changes

2023-11-28 11:46 UTC, merged