Redundant notifications [SCI-9788]
scinote-eln/scinote-web pull request #6750
Opened 2023-12-04 07:30 UTC by G-Chubinidze

Jira ticket: [SCI-9788](https://scinote.atlassian.net/browse/SCI-9788)

### What was done
_removed notifying current user of their actions_

2023-12-04 10:42 UTC, okriuchykhin commented on app/controllers/my_modules_controller.rb
>      users = User.where(id: params[:my_module][:user_ids])
users = User.where.not(id: current_user.id).where(id: params[:my_module][:user_ids])

2023-12-04 10:46 UTC, okriuchykhin commented on app/models/user_my_module.rb
> +    return if current_user == user
return if current_user.id == user.id

2023-12-04 10:46 UTC, okriuchykhin requested changes
check comments

2023-12-05 13:56 UTC, artoscinote approved these changes

2023-12-05 13:57 UTC, merged