Implement the Open Locally button on file previews [SCI-9757]
scinote-eln/scinote-web pull request #6821
Opened 2023-12-13 19:55 UTC by G-Chubinidze

Jira ticket: [SCI-9757](https://scinote.atlassian.net/browse/SCI-9757)

### What was done
_implement open locally button for file previews_

2023-12-18 08:43 UTC, aignatov-bio requested changes
Fix hound

2023-12-18 08:43 UTC, aignatov-bio commented on app/javascript/packs/vue/open_locally_menu.js
> +/* global notTurbolinksPreview */
Why this here?

2023-12-18 08:43 UTC, aignatov-bio commented on app/javascript/vue/shared/content/attachments/open_locally_menu.vue
> +            console.log(this.localAppName)
Remove

2023-12-18 08:43 UTC, aignatov-bio commented on app/views/shared/file_preview/_content.html.erb
> +          <open-locally-menu data="<%= AssetSerializer.new(asset, scope: { user: current_user }).to_json %>"/>
this must be done with remote request. Just add show action to AssetsController

2023-12-21 12:28 UTC, aignatov-bio requested changes
Fix hound

2024-01-16 13:03 UTC, artoscinote approved these changes

2024-01-16 13:03 UTC, merged