Add 12 well plate option - "Insert content" select menu (protocol, results, protocol template) [SCI-9839]
scinote-eln/scinote-web pull request #6836
Opened 2023-12-18 08:34 UTC by G-Chubinidze

Jira ticket: [SCI-9839](https://scinote.atlassian.net/browse/SCI-9839)

### What was done
_added new option and modified current one_

2023-12-18 08:45 UTC, aignatov-bio requested changes
Fix hound

2023-12-19 08:04 UTC, G-Chubinidze commented
> Fix hound

i've fixed whatever i could but hound still comments, the code is written ideally

2023-12-19 18:11 UTC, G-Chubinidze commented
@aignatov-bio  I've moved the export default to 0 indent but now the hound is giving off more errors, i dont want to touch them to avoid possible bugs.

2023-12-20 09:39 UTC, okriuchykhin approved these changes

2024-01-03 10:32 UTC, artoscinote approved these changes

2024-01-03 10:34 UTC, merged