Replace tasks table [SCI-9801]
scinote-eln/scinote-web pull request #6844
Opened 2023-12-19 13:23 UTC by aignatov-bio

Jira ticket: [SCI-9801](https://scinote.atlassian.net/browse/SCI-9801)

### What was done
Replace tasks table

2023-12-19 16:55 UTC, artoscinote requested changes
Please be careful not to mix designated_users (user_my_modules) and assigned_users (user_assignments)

2023-12-19 16:55 UTC, artoscinote commented on app/services/lists/my_modules_service.rb
> +      records = @raw_data.includes(PRELOAD)
all these method calls would probably be nicer if records was an instance variable @records, so we don't need to pass it everywhere

2023-12-19 16:55 UTC, artoscinote commented on app/javascript/packs/vue/my_modules_list.js
> +  window.myModulesList = null;
may be more proper to use `delete window.myModulesList` here

2023-12-19 16:55 UTC, artoscinote commented on app/javascript/vue/my_modules/list.vue
> +    usersFilterRenderer(option) {
would be nicer to group the renderer functions together, maybe at the end of the methods object

2023-12-19 16:55 UTC, artoscinote commented on app/javascript/vue/my_modules/modals/edit.vue
> +    validName() {
i think we should start sticking to some JS naming conventions, in this case (a boolean) it should be called `nameIsValid`

2023-12-19 16:55 UTC, artoscinote commented on app/serializers/lists/my_module_serializer.rb
> +    def assigned_users
**_designated_** users!

2023-12-19 16:55 UTC, artoscinote commented on app/services/lists/my_modules_service.rb
> +    def assigned_users_filter(my_modules, users)
**_designated_** users!

2023-12-19 16:55 UTC, artoscinote commented on app/javascript/vue/my_modules/renderers/assigned_users.vue
> +  name: 'AssignedUsersRenderer',
**_designated_** users!

2023-12-21 10:42 UTC, rekonder approved these changes

2023-12-21 12:26 UTC, merged