"Move" feature for multiple selected tasks and experiments (bulk action) [SCI-9840]
scinote-eln/scinote-web pull request #6865
Opened 2023-12-29 08:55 UTC by G-Chubinidze

Jira ticket: [SCI-9840](https://scinote.atlassian.net/browse/SCI-9840)

### What was done
_added bulk move_

2023-12-29 09:23 UTC, aignatov-bio requested changes

2023-12-29 09:23 UTC, aignatov-bio commented on app/views/experiments/_move_modal.html.erb
> +          <%= f.hidden_field :ids, multiple: true, value: experiment.id %>
you already have Ids in url object?

2023-12-29 09:23 UTC, aignatov-bio commented on app/controllers/experiments_controller.rb
> +    @experiments.each do |experiment|
This must be in transaction

2023-12-29 09:23 UTC, aignatov-bio commented on app/controllers/experiments_controller.rb
> +      move_responses << {message: message, path: path, status: status }
Just one message

2024-01-03 13:17 UTC, aignatov-bio requested changes

2024-01-03 13:17 UTC, aignatov-bio commented on app/controllers/experiments_controller.rb
> +    render json: move_response
It will not work with error request

2024-01-08 12:23 UTC, aignatov-bio requested changes

2024-01-18 11:58 UTC, aignatov-bio requested changes
Again not correct, check how it was done in my_modules move

2024-01-22 09:06 UTC, aignatov-bio requested changes

2024-01-22 09:06 UTC, aignatov-bio commented on app/controllers/experiments_controller.rb
> +    rescue StandardError => e
error handling must be different, because services works different

2024-01-22 09:06 UTC, aignatov-bio commented on app/controllers/experiments_controller.rb
> +      flash[:success] = t('experiments.table.move_success_flash', project: escape_input(project.name))
how this will work?

2024-01-23 13:32 UTC, artoscinote approved these changes

2024-01-23 13:32 UTC, merged