Implement button examples [SCI-10012]
scinote-eln/scinote-web pull request #6999
Opened 2024-01-24 09:12 UTC by G-Chubinidze

Jira ticket: [SCI-10012](https://scinote.atlassian.net/browse/SCI-10012)

### What was done
_implement button examples_

2024-01-25 14:54 UTC, aignatov-bio requested changes

2024-01-25 14:54 UTC, aignatov-bio commented on app/views/design_elements/_button.html.erb
> +<style>
Use tailwind

2024-01-25 14:54 UTC, aignatov-bio commented on app/views/design_elements/_button.html.erb
> +    <br>
Why so many `<br>` you can just use margin

2024-02-01 08:28 UTC, artoscinote approved these changes

2024-02-01 08:31 UTC, merged