Replace legacy vue components in Item Card [SCI-10177]
scinote-eln/scinote-web pull request #7098
Opened 2024-02-15 23:01 UTC by G-Chubinidze

Jira ticket: [SCI-10177](https://scinote.atlassian.net/browse/SCI-10177)

### What was done
_Replaced legacy vue components_

2024-02-16 11:07 UTC, aignatov-bio requested changes
Did you test? 
In new one we don't have - `change` action
And we don't have params - withEditCursor, withClearButton, isLoading, searchPlachrolder, customClass, optionsClassName

2024-02-16 11:11 UTC, G-Chubinidze commented
> Did you test? In new one we don't have - `change` action And we don't have params - withEditCursor, withClearButton, isLoading, searchPlachrolder, customClass, optionsClassName

Yes, no errors though, will double check and remove unnecessary params

2024-02-20 09:37 UTC, aignatov-bio requested changes

2024-02-20 09:37 UTC, aignatov-bio commented on app/javascript/vue/repository_item_sidebar/repository_values/RepositoryListValue.vue
>          @update="update"
And how update will work?

2024-02-20 09:43 UTC, G-Chubinidze commented on app/javascript/vue/repository_item_sidebar/repository_values/RepositoryListValue.vue
>          @update="update"
What do you mean?

2024-02-22 10:43 UTC, artoscinote approved these changes

2024-02-22 10:50 UTC, merged