(dev) Detect duplicated item IDs when parsing a spreadsheet [SCI-10399]
scinote-eln/scinote-web pull request #7291
Opened 2024-03-15 08:51 UTC by lasniscinote

Jira ticket: [SCI-10399](https://scinote.atlassian.net/browse/SCI-10399)

### What was done
- detecting items that have duplicates and skipping them
- displaying a warning message about duplicates

2024-03-17 12:03 UTC, lasniscinote commented on app/utilities/repository_import_parser/importer.rb
> +      counts.select { |item_id, count| count > 1 }.map { |item_id, count| { id: item_id, occurrences: count } }
hound is hallucinating again. It's clearly being used.

2024-03-25 09:47 UTC, artoscinote requested changes

2024-03-25 09:47 UTC, artoscinote commented on app/utilities/repository_import_parser/importer.rb
> +      arr_of_duplicates_ids = duplicates.pluck(:id)
don't use `arr_` prefix, plural is enough, i.e. `duplicate_ids`

2024-03-25 09:47 UTC, artoscinote commented on app/services/import_repository/parse_repository.rb
> +    def check_file_for_duplicates
Method name doesn't reflect what the method returns or does. Should probably be called just `duplicate_ids`

2024-03-25 09:47 UTC, artoscinote commented on app/services/import_repository/parse_repository.rb
> +      @sheet.to_a[1..].each do |inner_array|
use a map instead of empty array and each

2024-03-25 09:47 UTC, artoscinote commented on app/services/import_repository/parse_repository.rb
> +      arr_of_id_name_obj_pairs = []
`arr_` is redundant, `id_name_obj_pairs` is too vague

2024-03-25 09:47 UTC, artoscinote commented on app/controllers/repositories_controller.rb
> +    @importing_duplicates_warning = nil
redundant setting of instance variable to nil

2024-03-25 10:57 UTC, artoscinote approved these changes

2024-03-25 12:03 UTC, merged