Enable renaming attached files [SCI-10256]
scinote-eln/scinote-web pull request #7344
Opened 2024-03-21 09:27 UTC by ivanscinote

Jira ticket: [SCI-10256](https://scinote.atlassian.net/browse/SCI-10256)

### What was done
- enable renaming attached files

2024-03-25 10:34 UTC, artoscinote requested changes

2024-03-25 10:34 UTC, artoscinote commented on app/controllers/gene_sequence_assets_controller.rb
> +  def rename
this logic should probably be extracted into a concern, since it's basically the same for all controllers

2024-03-25 10:34 UTC, artoscinote commented on app/controllers/gene_sequence_assets_controller.rb
> +      render json: { error: 'File name must be at least 1 character long.' }, status: :unprocessable_entity
use translations

2024-03-27 10:39 UTC, ivanscinote commented on app/controllers/assets_controller.rb
> +  before_action :check_edit_permission, only: %i(edit destroy toggle_view_mode rename)
![Screenshot from 2024-03-27 11-38-52](https://github.com/scinote-eln/scinote-web/assets/138504771/fcb5c39d-d0d8-4e7a-a395-db25c94d4cc0)

2024-03-27 11:04 UTC, artoscinote approved these changes

2024-03-28 14:25 UTC, merged