Fix hover state for 'generate' docx report [SCI-10521]
scinote-eln/scinote-web pull request #7368
Opened 2024-03-26 10:09 UTC by sboursen-scinote

Jira ticket: [SCI-10521](https://scinote.atlassian.net/browse/SCI-10521)

### What was done
Fix hover state for 'generate' docx report.

2024-03-26 10:16 UTC, sboursen-scinote commented
The Docx report generation doesn't work
Fixing it ...

2024-03-26 10:30 UTC, sboursen-scinote commented
> The Docx report generation doesn't work Fixing it ...

Fixed

2024-03-27 09:26 UTC, aignatov-bio requested changes
First important thing: Dont use `hidden` there is conflict with bootstrap, we have `tw-hidden` so it proper works with tailwind.

And for this case you can just use opacity to hide show generate without modify cell. 
`opacity-0 hover:opacity-100`

2024-03-27 15:56 UTC, aignatov-bio approved these changes

2024-03-27 15:56 UTC, merged